my first pull request on github
HackYourFutureBelgium/class-15 pull request #27
Opened 2021-03-31 22:32 UTC by danielhalasz

2021-04-01 11:01 UTC, danielhalasz commented
---
name: student bio
about: A template PR for student bios
title: 'Daniel Halasz: bio'
labels: student-bio
---

<!--
  make this PR easy to find:

  - assign: yourself
  - milestone: precourse
-->

Quality checks:

- [x] My markdown code is tidy and contains no mistakes
- [x] I have previewed my bio and it looks the way I like it

<!--
  replace "x" with the number of your precourse issue
  an issue's number is listed when you search for it in the repo
-->

linked to #x

2021-04-01 14:11 UTC, colevandersWands requested changes

2021-04-01 14:11 UTC, colevandersWands commented on student-bios/danielHalasz.md
> +#
@danielhalasz , this is an extra header floating around.  You can remove it in this Pull Request by removing it in your fork. the Pull Request will update automatically

2021-04-01 15:44 UTC, danielhalasz commented on student-bios/danielHalasz.md
> +#
@colevandersWands thanks for the review, I have only kept it, because mardownlint suggested that it is incorrect, based on "MD041 - First line in a file should be a top-level heading"..anyway, I will remove it and update the PR

2021-04-01 15:58 UTC, colevandersWands commented on student-bios/danielHalasz.md
> +#
good point about the MD041. another fix could be to use the `#` header for your title instead of `##`.  Then you could get rid of the extra and avoid the error

2021-04-01 16:26 UTC, danielhalasz commented on student-bios/danielHalasz.md
> +#
okay I will do that, just wanted to have smaller font size in the first line :)

2021-04-02 09:25 UTC, colevandersWands commented on student-bios/danielHalasz.md
> +#
markdown is limited on purpose, it's meant to be easy to write and for making clear and consistent documentation.  Self-expression isn't top on it's list of priorities. 

looks good to me!

2021-04-02 09:26 UTC, colevandersWands approved these changes

2021-04-02 09:26 UTC, merged